# Union 쓰면 더 깔끔하다. 어차피 맛별로 죄다 더해야하니까
SELECT FLAVOR
    FROM (
        SELECT FLAVOR, TOTAL_ORDER FROM JULY
        UNION ALL
        SELECT FLAVOR, TOTAL_ORDER FROM FIRST_HALF
    ) AS ALL_ORDERS
    GROUP BY FLAVOR
    ORDER BY SUM(TOTAL_ORDER) DESC
    LIMIT 3;


# SELECT  J.FLAVOR
#     FROM (
#         SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_SUM
#             FROM JULY
#             GROUP BY FLAVOR
#     ) AS J
#     INNER JOIN (
#         SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_SUM
#             FROM FIRST_HALF
#             GROUP BY FLAVOR
#     ) AS F
#         ON J.FLAVOR = F.FLAVOR
#     ORDER BY (J.TOTAL_SUM + F.TOTAL_SUM) DESC
#     LIMIT 3