
SELECT  J.FLAVOR
    FROM (
        SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_SUM
            FROM JULY
            GROUP BY FLAVOR
    ) AS J
    INNER JOIN (
        SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_SUM
            FROM FIRST_HALF
            GROUP BY FLAVOR
    ) AS F
        ON J.FLAVOR = F.FLAVOR
    ORDER BY (J.TOTAL_SUM + F.TOTAL_SUM) DESC
    LIMIT 3


